INSTRUMENTS = {  
	AAAA: "Guitar",
	AAAB: "Drums",
	AAAC: "Piano",
	AAAD: "Voice"
}

STUDENT_LEVELS = {
	AAAA: "Beginner",
	AAAB: "Intermediate",
	AAAC: "Expert"
}

INSTRUCTOR_EXPERIENCE = {
	AAAA: "0 - 1 Years",
	AAAB: "1 - 3 Years",
	AAAC: "3 - 5 Years",
	AAAD: "5 - 10 Years",
	AAAE: " > 10 Years"
}

UI_ELEMENTS = {
	PICKER: "picker"
}

DEVELOPMENT_MODE = 0
PRODUCTION_MODE = 1

BRIDGE_NOTIFICATION_TEST = 0
BRIDGE_NOTIFICATION_NEW_MESSAGE = 1
BRIDGE_NOTIFICATION_NEW_LESSON_REQUEST = 2
BRIDGE_NOTIFICATION_LESSON_REQUEST_DENIED = 3
BRIDGE_NOTIFICATION_NEW_LESSON = 4

ERROR_NO_ERROR = 0